// mirrors backend/src/scripts/catalog/catalog.types.ts CATEGORY_KEYS - keeps browse order stable
export const CATEGORY_KEYS = [
    "vegetables",
    "fruits",
    "berries",
    "herbs",
    "mushrooms",
    "meat",
    "offal",
    "poultry",
    "fish",
    "seafood",
    "dairy",
    "eggs",
    "cheese",
    "grains_legumes",
    "pasta",
    "flour_baking",
    "nuts_seeds",
    "oils_fats",
    "spices",
    "sauces_vinegars",
    "sweeteners",
    "canned",
    "beverages",
] as const;
